version: "3.9"

services:
  db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  web:
    build: .
    container_name: auth_backend
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: authdb
      DB_USER: authuser
      DB_PASSWORD: authpass
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - app_net

  frontend:
    image: nginx:alpine
    container_name: auth_frontend
    volumes:
      - ./templates:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge
