# Generated by Django 5.2.6 on 2025-09-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='hackaton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soumission.hackaton'),
        ),
        migrations.AlterField(
            model_name='hackathonuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='hackathonuser',
            name='dateDelivrance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de delivrance'),
        ),
        migrations.AlterField(
            model_name='hackathonuser',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='hackathonuser',
            name='numeroCarteIdentite',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero CNIB/PASSPORT'),
        ),
        migrations.AlterField(
            model_name='hackathonuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
