# Generated by Django 5.2.6 on 2025-09-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0002_inscription_hackaton_alter_hackathonuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackaton',
            name='statut',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('fermer', 'fermer')], max_length=150, null=True),
        ),
    ]
