# Generated by Django 5.2.6 on 2025-09-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0003_hackaton_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackaton',
            name='dateFermeture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hackaton',
            name='dateOuverture',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
