# Generated by Django 5.2.6 on 2025-09-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0004_alter_hackaton_datefermeture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackaton',
            name='duree',
        ),
    ]
