# Generated by Django 5.2.6 on 2025-09-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0005_remove_hackaton_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='dossier_projet',
            field=models.FileField(blank=True, null=True, upload_to='dossier_projet/'),
        ),
    ]
