# Generated by Django 5.2.6 on 2025-09-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0006_inscription_cv_inscription_dossier_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateProgramme', models.DateField(blank=True, null=True)),
                ('programme', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hackaton', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soumission.hackaton')),
            ],
        ),
    ]
