# Generated by Django 5.2.6 on 2025-09-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0008_alter_programme_hackaton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackaton',
            name='user',
        ),
    ]
