# Generated by Django 5.2.6 on 2025-09-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumission', '0009_remove_hackaton_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon_partenaire/')),
            ],
        ),
    ]
